Add Just In Time support
rapid7/awsaml pull request #226
Opened 2023-07-20 15:23 UTC by anguyen-r7

[Add support for refreshing mechanism for Just In Time feature in Divvy.](https://github.com/rapid7/awsaml/pull/225)

2023-07-24 15:37 UTC, mmurrell-r7 commented
Failing Jenkins job can be ignored - due to unrelated issues with testing Git actions from the job. The code in this commit passes test and build requirements - see GH actions.

2023-07-25 18:39 UTC, dgreene-r7 requested changes

2023-07-25 18:39 UTC, dgreene-r7 commented on src/main/index.js
> +    Storage.delete('manager');
We shouldn't be trying to use the `Storage` class to serialize the manager anyway (remember all the errors we saw about serializing timers?) so you can probably just remove this.

2023-07-25 18:39 UTC, dgreene-r7 commented on src/main/index.js
> +protocol.registerSchemas();
I know that calling `registerHandlers` before the app is ready caused some errors. Might be worth moving this down to where we call `protocol.registerHandlers` just to be safe.

2023-07-25 18:39 UTC, dgreene-r7 commented on src/main/containers/refresh-jit.js
> +async function refreshJit(session = null) {
Do we ever expect a `session` object not to be provided here? If we'll always pass it we avoid providing a default value and instead explicitly check if the `session` is null and if so, do something actionable like throw an error.

2023-07-25 18:39 UTC, dgreene-r7 commented on src/main/containers/refresh-jit.js
> +  });
You're mixing `async/await` with `Promise` syntax which isn't inherently wrong (`async/await` is just sugar over promises anyway) but is just kind of an odd way of doing things. I'd rewrite it like this:
```suggestion
  const response = await fetch(session.apiUri, {
    method: 'GET',
    headers: session.header,
  })
  
  if (response.ok) {
    creds = await response.json();
  } else {
    Manager.removeByName(profileName);
    throw new Error('Unable to retrieve credentials from Divvy');
  }
```

Might also want a `try/catch` block around each call that you have to `await` just in case the promise rejects so we can return an error properly.

2023-07-25 18:39 UTC, dgreene-r7 commented on src/main/protocol.js
> +    return session.defaultSession.cookies.get({})
You can consolidate this call and the `cookies.find` call a few lines down by passing a filter object to the [`get` method](https://www.electronjs.org/docs/latest/api/cookies#cookiesgetfilter). If you're looking for the `session_id` cookie you could do:
```suggestion
    return session.defaultSession.cookies.get({
    	name: 'session_id',
    })
```
One thing to note is that `Array.find` used below returns the first element that matches the predicate regardless of whether more matches exist. I'd suggest trying to figure out an additional way of identifying the correct `session_id` cookie from ICS. Maybe domain matching or something?

2023-07-25 18:39 UTC, dgreene-r7 commented on src/main/protocol.js
> +      });
I'm not wild about mixing `Promises` and `async/await`. This could be rewritten to be much more legible like this:
```suggestion
    const cookies = await session.defaultSession.cookies.get({});
    sessionId = cookies.find((cookie) => cookie.name === 'session_id');
	  const body = await request.body.getReader().read();
    const reqBody = JSON.parse(Buffer.from(body.value).toString());
    const profile = {
      ...reqBody,
      roleName: reqBody.roleArn.split('/')[1],
      header: {
        'X-Auth-Token': sessionId.value,
      },
      apiUri: `https://${host}${pathname}`,
      showRole: false,
    };
    
    let data;
    try {
			data = await refreshJit(profile);
	  } catch (err) {
		  const body = JSON.stringify({
      	error_message: err?.message || 'unknown',
        error_type: err?.error_type || 'unknown',
      });
      return new Response(body, { status: 500 });
	  }
	  
  	const activeProfiles = Object.values(Manager.reloaders).map((r) => r.role);
  	data.activeProfiles = activeProfiles;
  	return new Response(JSON.stringify(data));
```

This is assuming the only place we expect the promise to reject is calling `refreshJit`. If it's not, then the `try/catch` should be extended around the places where we could end up in an error state.

2023-07-25 19:00 UTC, anguyen-r7 commented on src/main/index.js
> +protocol.registerSchemas();
When I put this line [here](https://github.com/rapid7/awsaml/blob/13e0cc972d1418d70e16e8bed61801e5485b13cd/src/main/index.js#L73) where `protocol.registerHandlers` is I get the following error: 

```
UnhandledPromiseRejectionWarning: Error: protocol.registerSchemesAsPrivileged should be called before app is ready
```

2023-07-25 19:41 UTC, anguyen-r7 commented on src/main/api/reloader/reloader.js
> +  }) {
Eslint does complain

2023-07-27 13:27 UTC, dgreene-r7 reviewed
One small stylistic thing. Once you clear that up and any linting errors this one's good to go!

2023-07-27 13:27 UTC, dgreene-r7 commented on src/main/containers/refresh-jit.js
> +  }).catch((err) => {
If you're using `async/await`	the general pattern is to use `try/catch` blocks to do error handling  vs calling the `catch` method on the promise.

2023-07-27 14:17 UTC, dgreene-r7 approved these changes
Looks great! Nice job 😄

2023-07-27 15:17 UTC, merged